---
title: Sam Joan Roque-Worcel
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: sam@roque-worcel.com
description: My blog covering coding, security, game development and code challenges.
baseurl: ''
url: ''
github_username: samjoan
theme: minima
plugins:
- jekyll-feed
