---
title: Sam's blog
timezone: Pacific/Auckland
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: sam[_].roque-worcel.com
description: 'My blog covering coding, security, game development and code challenges.
  No AI was used in writing this nonsense. Opinions my own and not anyone else''s
  :) '
baseurl: 
url: 
github_username: samjoan
theme: minima
plugins:
- jekyll-feed
gitlab_username: sroque-worcel
