---
title: Sam's blog
timezone: Pacific/Auckland
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: sam[_].roque-worcel.com
description: My blog covering coding, security, game development and code challenges.
baseurl: 
url: 
github_username: samjoan
theme: minima
plugins:
- jekyll-feed
Field name: 
